#!/usr/bin/env python
import argparse
from bucoffea.helpers.merging import CoffeaMerger


def parse_commandline():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "indir",
        type=str,
        help="The input directory holding the coffea files to be merged.",
    )
    parser.add_argument(
        "--jobs",
        "-j",
        type=int,
        default=1,
        help="The number of cores to use for merging.",
    )
    parser.add_argument(
        "--outdir",
        "-o",
        type=str,
        default="INDIR/merged",
        help="The output directory to use.",
    )

    args = parser.parse_args()
    if "INDIR" in args.outdir:
        args.outdir = args.outdir.replace("INDIR", args.indir)


    return args


def main():
    args = parse_commandline()
    cm = CoffeaMerger(indir=args.indir, jobs=args.jobs)
    cm.to_klepto_dir(args.outdir)


if __name__ == "__main__":
    main()
